name: Security Vulnerability
description: Report a security vulnerability (please use GitHub Security Advisories for sensitive issues)
title: "[Security]: "
labels: ["security", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## Security Vulnerability Report

        **IMPORTANT**: If this is a sensitive security issue that could put users at risk,
        please DO NOT use this public issue form. Instead, report it privately via:
        - GitHub Security Advisories (preferred)
        - Email to security@stegvault.dev (in future)

        This form should only be used for non-sensitive security improvements or concerns.

  - type: checkboxes
    id: severity
    attributes:
      label: This is NOT a critical vulnerability
      description: Confirm this issue does not expose user data or cryptographic keys
      options:
        - label: I confirm this is not a critical security vulnerability
          required: true

  - type: textarea
    id: description
    attributes:
      label: Security Concern Description
      description: Describe the security concern or vulnerability
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - Cryptography
        - Input Validation
        - Dependency Vulnerability
        - Information Disclosure
        - Documentation Security Gap
        - Other
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Potential Impact
      description: What is the potential impact of this issue?
    validations:
      required: true

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: Do you have suggestions for how to address this?
    validations:
      required: false